---
- name: install packages
  package:
    name:
      - samba
      - samba-common
      - krb5-user
      - krb5-config
      - libnss-sss
      - winbind
      - libpam-winbind
      - libnss-winbind
    state: present

- name: template /etc/krb5.conf
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0600

- name: template nsswitch.conf
  template:
    src: nsswitch.conf.j2
    dest:  /etc/nsswitch.conf
    owner: root
    group: root
    mode: 0600

- name: template /etc/samba/smb.conf
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: 0600
#  notify: 
#    - restart smbd

- name: Make home directory
  lineinfile:
    path: /etc/pam.d/common-session
    line: 'session    required    pam_mkhomedir.so skel=/etc/skel/ umask=0022'
#  notify: restart sssd



