---
- name: install sssd packages
  package:
    name:
      - sssd
    state: present

- name: template nsswitch.conf
  template:
    src: nsswitch.conf.j2
    dest:  /etc/nsswitch.conf
    owner: root
    group: root
    mode: 0600

- name: Make home directory
  lineinfile:
    path: /etc/pam.d/common-session
    line: 'session    required    pam_mkhomedir.so skel=/etc/skel/ umask=0022'
#  notify: restart sssd



